/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sleepydragon.capbutnbrightness.clib;

public interface CLibConstants {
  public final static int EACCES = CLibJNI.EACCES_get();
  public final static int EBADF = CLibJNI.EBADF_get();
  public final static int EFAULT = CLibJNI.EFAULT_get();
  public final static int ELOOP = CLibJNI.ELOOP_get();
  public final static int ENAMETOOLONG = CLibJNI.ENAMETOOLONG_get();
  public final static int ENOENT = CLibJNI.ENOENT_get();
  public final static int ENOMEM = CLibJNI.ENOMEM_get();
  public final static int ENOTDIR = CLibJNI.ENOTDIR_get();
  public final static int EOVERFLOW = CLibJNI.EOVERFLOW_get();
  public final static int EPERM = CLibJNI.EPERM_get();
  public final static int EROFS = CLibJNI.EROFS_get();
  public final static int S_IRUSR = CLibJNI.S_IRUSR_get();
  public final static int S_IWUSR = CLibJNI.S_IWUSR_get();
  public final static int S_IXUSR = CLibJNI.S_IXUSR_get();
  public final static int S_IRWXU = CLibJNI.S_IRWXU_get();
  public final static int S_IRGRP = CLibJNI.S_IRGRP_get();
  public final static int S_IWGRP = CLibJNI.S_IWGRP_get();
  public final static int S_IXGRP = CLibJNI.S_IXGRP_get();
  public final static int S_IRWXG = CLibJNI.S_IRWXG_get();
  public final static int S_IROTH = CLibJNI.S_IROTH_get();
  public final static int S_IWOTH = CLibJNI.S_IWOTH_get();
  public final static int S_IXOTH = CLibJNI.S_IXOTH_get();
  public final static int S_IRWXO = CLibJNI.S_IRWXO_get();
  public final static int S_ISUID = CLibJNI.S_ISUID_get();
  public final static int S_ISGID = CLibJNI.S_ISGID_get();
  public final static int S_ISVTX = CLibJNI.S_ISVTX_get();
}
