/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sleepydragon.capbutnbrightness.clib;

public class CLib implements CLibConstants {
  public static int stat(String path, Stat buf) throws org.sleepydragon.capbutnbrightness.clib.ClibException {
    return CLibJNI.stat(path, Stat.getCPtr(buf), buf);
  }

  public static int chmod(String path, int mode) throws org.sleepydragon.capbutnbrightness.clib.ClibException {
    return CLibJNI.chmod(path, mode);
  }

}
