/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sleepydragon.capbutnbrightness.clib;

public class Stat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Stat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Stat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CLibJNI.delete_Stat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

static {
    System.loadLibrary("CLib");
}

  public void setMode(long value) {
    CLibJNI.Stat_mode_set(swigCPtr, this, value);
  }

  public long getMode() {
    return CLibJNI.Stat_mode_get(swigCPtr, this);
  }

  public void setUid(long value) {
    CLibJNI.Stat_uid_set(swigCPtr, this, value);
  }

  public long getUid() {
    return CLibJNI.Stat_uid_get(swigCPtr, this);
  }

  public void setGid(long value) {
    CLibJNI.Stat_gid_set(swigCPtr, this, value);
  }

  public long getGid() {
    return CLibJNI.Stat_gid_get(swigCPtr, this);
  }

  public Stat() {
    this(CLibJNI.new_Stat(), true);
  }

}
